---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: concourse_test_setup2
  - name: dependency-cache

run:
  path: concourse_test_setup2/ci/scripts/run_tests.sh